### ISSUE TITLE
Wrong URL on README.md

### ISSUE THREAD

**Issue by ftonato** [gpedro/node-vagalume#10]
A url do método *getByTrecho(trecho, [limite])* no [README.md](https://github.com/gpedro/node-vagalume#getbytrechotrecho-limite) está indo p/ uma página não encontrada (404).

A url correta p/ tal descrição [seria essa](http://api.vagalume.com.br/docs/search/#mus)?

/cc @gpedro

**Comment by gpedro** [comment]
poderia me mandar um PR?

**Comment by ftonato** [comment]
Será uma honra :+1:
