### ISSUE TITLE
Add API Key support

### ISSUE THREAD

**Issue by ftonato** [gpedro/node-vagalume#9]
Conforme descrição do projeto:

**IMPORTANTE**: Para usar Vagalume API, é necessário que seu aplicativo tenha [credenciais de autorização](https://auth.vagalume.com.br/). Cadastre-se no Vagalume e crie sua chave de API. Esta credencial será requerida a partir do dia **23/11/2015**.

Poderíamos fazer a atualização conforme indica a [issue que explica como deve ser o novo padrão nas requisições](https://github.com/vagalume/api-exemplos/issues/20).

Exemplo no método _getNoticias()_

``` javascript
PUBLIC.getNoticias = function () {
  return PRIVATE.wwwRequest('/news/index.js?apikey={'+apiKey+'}');
};
```

Algumas ideias de como receber esse valor:
1. O método a ser usado podería receber esse valor. **Acho que não é a melhor opção**
2. A função `Vagalume` podería receber  esse valor `var api = new Vagalume('valor_apiKey');` **Acho que essa é a melhor opção**

O que acha @gpedro ?

**Comment by gpedro** [comment]
olá @ftonato,

efetuei alguns testes de implementação do apikey e vi que essa história de VagalumeAPI não está nada instável :( 

* não passando está funcionando.
* passando a key, eu caio em uma página do nginx o.O

de qualquer forma, tenho que dar relida na API novamente e adicionar os novos métodos (:

**Comment by ftonato** [comment]
@gpedro 

Acabei de fazer um teste aqui e percebi que, o método *getNoticias()* como mostrado acima e está funcionando (com o apiKey), todavia também funciona sem o apiKey :fearful: 

Fiz o mesmo teste p/ o método *getRank()* (com apiKey e sem apiKey) e ambos ainda estão funcionando :fearful: 

De toda forma, se 'todos' os métodos funcionarem com a apiKey (o que vai contra o que disse, pois no seu teste não funcionou), poderíamos adicionar o suporte ao apiKey desde já!

**Comment by ftonato** [comment]
Fala @gpedro, como o projeto parece não ser mais receber atualizações, encerrarei a _issue_ por hora, mas poderemos voltar a discutir isso em um futuro...

Abraço,
